.github/CODEOWNERS
=> META: configure code owners

build/ci-build.yml, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj
Fix packages to push to MyGet
Closes #7
=> Fix packages to push to MyGet

README.md
Provide README:
- Provide NuGet badge
- Provide CI badge
Closes #1
Closes #4
Closes #6
=> Provide README

build/nuget-release.yml
This was optimized in template via https://github.com/arcus-azure/azure-devops-templates/pull/25
=> Remove conditions for GitHub releases

build/ci-build.yml, build/nuget-release.yml
Use variable group for secrets in CI/release
=> Use variable group for secrets in CI/release

src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/ServiceBus/EmptyMessagePump.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs
=> FEAT: add Azure ServiceBus Queue/Topic MessagePump registration shortcuts

.gitignore, docs/features/message-pumps/service-bus.md, docs/index.md
Provide documentation for Azure Service Bus message pump.
Closes https://github.com/arcus-azure/arcus.messaging/issues/14
=> Provide documentation for Azure Service Bus message pump

build/ci-build.yml
Provide display name for getting container logs
=> Provide display name for getting container logs

.gitignore, build/ci-build.yml, build/nuget-release.yml, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/Fixture/CommandArgument.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusWorkerProject.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TestConfig.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/MessagePumpService.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusEntity.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpDockerTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Integration/appsettings.json, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/Dockerfile, src/Arcus.Messaging.Tests.Workers.ServiceBus/Program.cs, src/Arcus.Messaging.sln
In upcoming additional functionality of the message pump, it's useful to have a maintainable testing approach so different type of message pump configurations can be tested.
=> FEAT: provide maintainable message pump testing approach

docs/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePumpSettings.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Program.cs
=> FIX: reuse subscription across topic message pumps

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj
Relates to https://github.com/arcus-azure/arcus/issues/50
=> Chore - update Messaging projects with netcore3.0 FrameworkReference

docs/features/message-pumps/service-bus.md
Relates to #https://github.com/arcus-azure/arcus.messaging/issues/23
=> Docs - add feature docs for message correlation

docs/features/message-pumps/service-bus.md
=> Docs - add feature docs for message handler

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueAndTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpDockerTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Arcus.Messaging.Tests.Workers.ServiceBus.Queue.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Arcus.Messaging.Tests.Workers.ServiceBus.Topic.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers/Arcus.Messaging.Tests.Workers.csproj, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersMessageHandler.cs
=> Feature - multiple message pump instances

src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs
=> Feature - stricten MessageHandler filter to substract 'IMessageHandler<,>' implementations

build/ci-build.yml, build/nuget-release.yml, build/variables/build.yml, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusWorkerProject.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs
Relates to https://github.com/arcus-azure/arcus/issues/46
=> Chore/Test - move build variables to variable template

docs/features/message-pumps/customization.md, docs/features/message-pumps/service-bus.md, docs/features/service-bus.md, docs/index.md
Closes https://github.com/arcus-azure/arcus.messaging/issues/43
=> Docs - describe customization in message pump

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.Tests.Core/Arcus.Messaging.Tests.Core.csproj, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj
=> Move away from preview Arcus packages

src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
=> Provide less verbose logs for plumbing

src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs
Provide less verbose logs for TCP health probing
=> Provide less verbose logs for TCP health probing

src/Arcus.Messaging.ServiceBus.Core/Extensions/MessageExtensions.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/MessageExtensionsTests.cs
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
Provide capability to specify custom transaction id user property to get correlation info
=> Provide capability to specify custom transaction id user property to get correlation info

src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusClient.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
=> Provide better telemetry out-of-the-box

src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs
Apparently, also something we missed, probably due to the non-required CI build.
=> Fix - invalid Serilog formatting

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/IAzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/IAzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/MessageHandling/IMessageHandler.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs
Cleaning some XML code docs of the new message routing/handling types.
=> feat: clean-up xml code docs

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj
Relax enforcement of dependencies as I was too 🥵
=> fix: Relax enforcement of dependencies

src/Arcus.Messaging.Tests.Unit/Fixture/OrderV1AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Unit/Fixture/OrderV2AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs
Adds unit test for more extreme input; just to be sure that we can handle a bigger amount.
Closes #208
=> test: more extreme az service bus message routing tests

docs/preview/guides/migration-guide-v1.0.md, docs/preview/index.md
Add proposal for the migration guide for v1.0.
Closes #202
=> docs: add migration guide for v1.0

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs
Adds Azure Service Bus request tracking to the message router so that every processed message is also tracked as an incoming request in Azure Application Insights.
Closes #221
=> feat: add az servicebus request tracking to message router

docs/preview/01-index.md
Adds an introduction paragraph to the welcome page.
Closes #278
=> docs: add introduction paragraph to welcome page

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.AzureFunctions.ServiceBus/Arcus.Messaging.AzureFunctions.ServiceBus.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj
Adds package readme project tag in project files.
Relates to https://github.com/arcus-azure/arcus/issues/209
=> chore: add package readme project tag

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs
Add request telemetry tracking to missing general message routing.
Closes #316
=> feat: add request tracking az servicebus general routing

docs/preview/02-Features/02-message-handling/01-service-bus.md, docs/preview/02-Features/02-message-handling/02-service-bus-azure-functions.md, docs/preview/02-Features/02-message-handling/04-customize-general.md, docs/preview/03-Guides/migration-guide-v1.0.md
Remove tables of contents on all feature docs pages as this is generated by the frontend build.
=> docs: remove table of contents

src/Arcus.Messaging.Abstractions.EventHubs/MessageHandling/AzureEventHubsMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj
Use EventHubs request tracking in EventHubs message router.
=> feat: add eventhubs request tracking

src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrderV2AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersAzureServiceBusAbandonFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersAzureServiceBusAbandonMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/Extensions/IEventGridPublisherExtensions.cs
Re-use order publishing extension in test message handlers.
Closes #343
=> chore: remove order publishing duplication

src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
Use better logging when message pumps are cancelled.
Closes #321
=> chore: update cancelled logging

src/Arcus.Messaging.Tests.Runtimes.AzureFunction.ServiceBus.Topic/local.settings.json
Missed file that should not be in source control.
=> fix: delete `local.settings.json` from source control

docs/preview/02-Features/02-message-handling/01-service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpSettings.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusQueueMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/AzureServiceBusMessagePumpOptionsTest.cs
Allow to configure the `PrefetchCount` on the ServiceBus message pump.
Closes #426
=> feat: Allow configurable PrefetchCount

docs/preview/02-Features/02-message-handling/01-service-bus.md, docs/preview/02-Features/02-message-handling/03-event-hubs.md, docs/versioned_docs/version-v2.0.0/02-Features/02-message-handling/01-service-bus.md, docs/versioned_docs/version-v2.0.0/02-Features/02-message-handling/03-event-hubs.md
Correct documentation w/ moved routing options.
Closes #447
=> docs: correct moved routing options

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj
Slim down the used NuGet packages throughout the solution, both transient and unused.
=> chore: slim down used nuget packages

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs
Add reason for dead-lettering in Azure Service bus message router.
Closes #460
=> chore: add dead-letter reason

src/Arcus.Messaging.Abstractions/PropertyNames.cs
Remove the property `ContentType` from class `PropertyNames`.
=> chore(propertynames): remove property propertynames.contenttype

src/Arcus.Messaging.Abstractions/PropertyNames.cs
Remove `TransactionId` from `PropertyNames`.
=> chore(messaging.abstractions): remove propertynames.transactionid
