arcus-azure/arcus.messaging

src/Arcus.Messaging.Health/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tcp.Orchestrator.dcproj, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs, src/Arcus.Messaging.Tests.Worker/Program.cs
Provide a convenient way to opt-in for TCP health probing.
- Introduce `AddTcpHealthProbes` to opt-in and allow you to register health checks, if you want
```csharp
.ConfigureServices((hostContext, services) =>
{
services.AddTcpHealthProbes(healthCheckBuilder =>
{
healthCheckBuilder.AddCheck("sample", () => HealthCheckResult.Healthy());
});
});
```
```csharp
.ConfigureServices((hostContext, services) =>
{
services.AddTcpHealthProbes();
services.AddHealthChecks()
.AddCheck("sample", () => HealthCheckResult.Healthy());
});
```
Relates to #11
=> Provide a convenient way to opt-in for TCP health probing

docs/features/tcp-health-probe.md, docs/index.md
Adds feature docs for the TCP health probe.
Relates to #11
Ps.: the folder structure will probably change when more features are added; so I added this feature docs at the root of the `./features` folder.
=> DOC: add feature docs for TCP health probe

src/Arcus.Messaging.Tests.Integration/Health/HealthReportEntryConverter.cs, src/Arcus.Messaging.Tests.Integration/Health/HealthReportEntryConverterTests.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs, src/Arcus.Messaging.Tests.Worker/Program.cs
Fixes how we deserializat the `HealthReport`.
The problem exists in that the report is made for serialization but not _deserialization_. The entries are `struct`'s and don't get deserialized correctly.
This could be fixed with a dedicated `JsonConverter` that get passed with the deserialization call.
Relates to #21
=> FIX: health report deserialization with individual check

docs/features/tcp-health-probe.md, src/Arcus.Messaging.Health/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Health/IHealthReportSerializer.cs, src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Health/Tcp/TcpHealthListenerOptions.cs, src/Arcus.Messaging.Tests.Worker/Program.cs
Adds a `TcpHealthListenerOptions` to the services collection so we can control the serialization of the `HealthReport` and the TCP port of the health check endpoint.
Closes #18 
Closes #20
=> FEAT: make HealthReport serialization & TCP health port configurable

src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs
Provide overload that doesn't require queue name, only secret name.
This is to support connection strings scoped to the queue itself.
Follow-up of #50
=> Provide overload that doesn't require queue name

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueAndTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicProgram.cs
Closes https://github.com/arcus-azure/arcus.messaging/issues/58
=> Feature - add 'JobId' to log messages in the Azure Service Bus message pump

src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpConfiguration.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpSettings.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusQueueMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusTopicMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueAndTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicProgram.cs
We could also provide some custom return type if that's necessary or more user-friendly.
I think this (or something simulair) is required if we want to control JSON deserialization since in previous versions (without message handlers) we already could do that so we should keep that functionality.
Relates to #43
=> Feature - make customized message pump still available with indroduction of message handlers

docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpConfiguration.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/Fixture/KeyRotationConfig.cs, src/Arcus.Messaging.Tests.Integration/Fixture/KeyVaultSecret.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueue.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueKeyVaultProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServicePrincipal.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TestConfig.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Integration/ServiceBus/ServiceBusClient.cs, src/Arcus.Messaging.Tests.Integration/appsettings.json, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/Program.cs
Provides the functionality so that the message pump automatically re-authenticate when the Azure Service Bus connecting string is rotated.
Closes #37
=> Feature - rotate service bus connection string connection

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Integration/ServiceBus/ServiceBusClient.cs
Change the key rotation by using the Azure Service Bus Primary connection string key first and moving on to the Secondary connection string key on rotation.
Closes #100
=> Feature - change Azure Service Bus connection string key rotation flow w/ Primary & Secondary keys

docs/preview/features/message-pumps/customization.md, docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.Abstractions/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/IFallbackMessageHandler.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandlerResult.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/IAzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithServiceBusFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/Fixture/PassThruFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Unit/Fixture/PassThruServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/IServiceCollectionTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/MessageHandlerTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersServiceBusFallbackMessageHandler.cs
Adds an extra interface `IFallbackMessageHandler` that will handle remaining messages if none of the message handlers were able to handle the message.
- Added service collection extension to register this more easily
- Added section in customization docs to explain this feature
- Added integration test that will explicitly test the fallback of the message to the handler
- Added extensions unit tests
Closes #110
=> Feature - add fallback message handler as safety net during message handing

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
When the Azure Service Bus message is being handled but fails during processing, the exception should not only be logged, but also be re-thrown so the message is marked abannoned.
Closes #115
=> Fix - rethrow when message handling failed

build/ci-build.yml, build/nuget-release.yml, docs/preview/features/message-pumps/customization.md, docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/IAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/AzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/AzureServiceBusMessageHandlerTemplate.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithServiceBusDeadLetterFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithServiceBusDeadLetterProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicWithServiceBusAbandonFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicWithServiceBusAbandonProgram.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusAbandonFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusAbandonMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusDeadLetterFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusDeadLetterMessageHandler.cs
Provide the capability to influence the Azure Service Bus operations during the message handling.
- Adds `AzureServiceBusMessageHandler<>`: with `DeadLetterMessageAsync` and `AbandonMessageAsync` methods
- Adds `AzureServiceBusFallbackMessageHandler<>`: with `DeadLetterAsync` and `AbandonAsync` methods
- Adds 4 integration tests to test the four different ways of deadlettering/abanoning the message
- Updates the (preview) feature docs with examples
Closes #118
=> Feature - provide specific Azure Service Bus message operations during message handling

build/ci-build.yml, build/nuget-release.yml, src/Arcus.Messaging.Tests.Integration/Fixture/TestConfig.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpDockerTests.cs, src/Arcus.Messaging.Tests.Integration/appsettings.json
Use speparate Azure resources for Docker integration tests so it can run more safely in parallel with the self-contained integration tests.
Closes #121
=> Chore - separate Docker integration tests Azure resources

docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/AzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Pumps.ServiceBus/MessageHandling/AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueCompleteProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicFallbackCompleteProgram.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusCompleteMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersFallbackCompleteMessageHandler.cs
Add the `.CompleteMessageAsync` and the `.CompleteAsync` to the respectively (regular) and fallback specific Azure Service Bus message handler templates.
Closes #128
=> Feature - add completion message to specific Azure Service Bus influence message handler

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/Fixture/ApplicationInsightsConfig.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueTrackCorrelationOnExceptionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TestConfig.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/appsettings.json, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersSabotageAzureServiceBusMessageHandler.cs
Moved the try/catch/track block inside the correlation information scope.
This wasn't the case which meant that exceptions where tracked without correlation information.
Related to #132
=> Fix - include correlation information when tracking exceptions

src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Pumps.Abstractions/MessageHandling/MessageHandlerRegistration.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueContextPredicateSelectionWithDeadLetterProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicContextPredicateSelectionWithDeadLetterProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicContextPredicateSelectionWithServiceBusAbandonProgram.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs
The problem existed when we tried to use both the context filtering as the Azure Service Bus operations when handling a message.
By hiding how we determine the type and instance of the message handler, we're more in control and can cirvumvent this problem.
Closes #134
=> Fix - combine context predicate w/ Service Bus operations

docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpConfiguration.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpSettings.cs
Make sure that we track the retrieval of the Azure Service Bus connection string when the message pump requests this.
=> Feature - log security event upon Azure Service Bus connection string retrieval

docs/features/message-pumps/customization.md, docs/features/message-pumps/service-bus.md, docs/features/service-bus.md, docs/features/tcp-health-probe.md, docs/preview/features/message-pumps/customization.md, docs/preview/features/message-pumps/service-bus.md, docs/preview/features/service-bus.md, docs/preview/features/tcp-health-probe.md, docs/v0.1.0/features/message-pumps/customization.md, docs/v0.1.0/features/message-pumps/service-bus.md, docs/v0.1.0/features/service-bus.md, docs/v0.1.0/features/tcp-health-probe.md, docs/v0.2.0/features/message-pumps/customization.md, docs/v0.2.0/features/message-pumps/service-bus.md, docs/v0.2.0/features/service-bus.md, docs/v0.2.0/features/tcp-health-probe.md, docs/v0.3.0/features/message-pumps/customization.md, docs/v0.3.0/features/message-pumps/service-bus.md, docs/v0.3.0/features/service-bus.md, docs/v0.3.0/features/tcp-health-probe.md, docs/v0.4.0/features/message-pumps/customization.md, docs/v0.4.0/features/message-pumps/service-bus.md, docs/v0.4.0/features/service-bus.md, docs/v0.4.0/features/tcp-health-probe.md, docs/v0.5.0/features/message-pumps/customization.md, docs/v0.5.0/features/message-pumps/service-bus.md, docs/v0.5.0/features/service-bus.md, docs/v0.5.0/features/tcp-health-probe.md
Adds the missing `using` statements to the feature docs.
Relates to https://github.com/arcus-azure/arcus/issues/107
=> Docs - add missing 'usings' to feature docs

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Arcus.Messaging.Tests.Workers.ServiceBus.Queue.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Arcus.Messaging.Tests.Workers.ServiceBus.Topic.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers/Arcus.Messaging.Tests.Workers.csproj
Fixes the `netcoreapp3.1` dependencies like we did in the security repo. Also update the [KeyVault dependencies](https://www.nuget.org/packages/Microsoft.Azure.KeyVault/3.0.4) to a greater version so it uses System.Net.Http v4.3.4 which fixes a DoS vulnerability.
See https://app.snyk.io/org/arcus/project/26a983f2-be5e-49d2-b277-f35344b13b60/pr-check/4f507eae-f8fa-43e5-ab9a-14876f9d8b15
=> Fix - netcoreapp3.1 dependencies plus security vulnerabilities

docs/preview/features/tcp-health-probe.md, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Health/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Health/IHealthReportSerializer.cs, src/Arcus.Messaging.Health/Publishing/TcpHealthCheckPublisher.cs, src/Arcus.Messaging.Health/Tcp/CustomTcpListener.cs, src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Health/Tcp/TcpHealthListenerOptions.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TcpConnectionRejectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/WorkerProject.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerDockerTests.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthService.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Program.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/Program.cs
Adds an `IHealthReportPublisher` that changes the TCP availability of the `TcpHealthListener` based on the health report status code.
Closes #131
=> Feature - add support to reject TCP client connections based on health report status

src/Arcus.Messaging.Health/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Health/Publishing/TcpHealthCheckPublisher.cs, src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueAndTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueContextAndBodyFilterSelectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueContextTypeSelectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueKeyVaultProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueTrackCorrelationOnExceptionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithContextAndBodyFilterAndBodySerializerProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusQueueWithServiceBusFallbackProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicBodyPredicateSelectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicContextPredicateSelectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/ServiceBusTopicWithOrderBatchProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TcpConnectionRejectionProgram.cs, src/Arcus.Messaging.Tests.Integration/Fixture/WorkerProject.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/Program.cs
Some small improvement that makes sure that we don't register a unnecessary resource which will be called regularly when publishing health, when we don't need it.
=> Fix - only register health publisher when required

docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusCorrelationOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpConfiguration.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Tests.Unit/Blanks.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/AzureServiceBusMessagePumpOptionsTest.cs
Introduces a new property in the settings which can control the name of correlation transaction ID of the Azure Service Bus message during receival of Azure Service Bus messages in the message pump.
Closes #156
=> Feature - make message correlation transaction ID configurable

src/Arcus.Messaging.ServiceBus.Core/Extensions/MessageExtensions.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/MessageExtensionsTests.cs
Update the message correlation extraction to initialize like the operation ID the transaction ID with a default guid when none is found.
Closes #158
=> Feature - initialize the transaction ID (like the operation ID) with default guid

src/Arcus.Messaging.Tests.Unit/ServiceBus/MessageExtensionsTests.cs
Not sure how it happened, but the unit test about the transaction ID failed on `master`.
=> Fix - unit test to verify that non-existing transaction ID is 'null'

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/MessageCorrelationInfo.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Abstractions/PropertyNames.cs
* Deprecated 'packageUrl' of the NuGet that's being ignored for now
* Nullable reference types removed to be more compatible
* Add public XML code docs
=> chore: resolve code warnings

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus.KeyRotation/Arcus.Messaging.Pumps.ServiceBus.KeyRotation.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj
Let's use package version ranges for the Arcus dependencies to make it more stable.
Relates to https://github.com/arcus-azure/arcus/issues/129
=> feat: use package version ranges for Arcus dependencies

src/Arcus.Messaging.Abstractions.ServiceBus/AzureServiceBusSystemProperties.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/AzureServiceBusSystemPropertiesTests.cs
Adds the necessary unit tests to verify a correct assignment to our system properties type.
Closes #185
=> test: add unit tests for az servicebus sys props assignments

src/Arcus.Messaging.Tests.Integration/Extensions/ServiceBusConnectionStringPropertiesExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs
Add Azure Service Bus namespace-scoped integration tests that pass in the entity path separately so we can verify that the bug (#187) is indeed solved by the revisiting of the settings and the use of the new Azure SDK.
Closes #187 
Relates to #179 
Relates to #175
=> test: add az servicebus namespace-scoped integration tests

docs/preview/features/message-pumps/service-bus.md, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusAbandonFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusDeadLetterFallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersFallbackCompleteMessageHandler.cs
Use always the `Message` part when calling specific Azure Service Bus operations (dead letter, complete...) in the fallback message handlers.
Closes #194
=> feat: streamline `Message` part in az servicebus fallback message handlers

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj, src/Arcus.Messaging.Tests.Contracts/Arcus.Messaging.Tests.Contracts.csproj, src/Arcus.Messaging.Tests.Core/Arcus.Messaging.Tests.Core.csproj, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/MessagePump/TestMessagePumpService.cs, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/ServiceBus/KeyRotation/AzureServiceBusKeyRotationTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Arcus.Messaging.Tests.Workers.ServiceBus.Queue.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Program.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Arcus.Messaging.Tests.Workers.ServiceBus.Topic.csproj, src/Arcus.Messaging.Tests.Workers/Arcus.Messaging.Tests.Workers.csproj
Fix dependency ranges for v1.0.0-preview-1 which are blocking me from upgrading since it enforces Arcus Observability < v1.0
=> fix: Use reasonable dependency ranges to unblock v1.0.0-preview-1

src/Arcus.Messaging.Abstractions.ServiceBus/InternalsVisibleTo.cs
Was first introduced to give access to the message handling functionality from the Azure Service Bus project.
But since we extracted this into routers, we can reference a router instead of internal message handling logic.
=> fix: remove internals visible to attribute

src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
When creating custom message router (like the CloudEvents message router in the background jobs repo), we could benefit from the message pump options and therefore the message router options, but then we need to have access to the message router options directly.
Closes #212
=> feat: make message routing options public for custom routers

src/Arcus.Messaging.Pumps.ServiceBus/TopicSubscription.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs
Re-introduce the `None` enum member for the `TopicSubscription` enumeration as to make the Azure Service Bus Topic configuration more explicit.
Closes #216
=> fix: re-introduce 'None' enum member for az service bus topic sub

src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Tests.Contracts/Arcus.Messaging.Tests.Contracts.csproj, src/Arcus.Messaging.Tests.Core/Arcus.Messaging.Tests.Core.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Queue/Arcus.Messaging.Tests.Workers.ServiceBus.Queue.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Arcus.Messaging.Tests.Workers.ServiceBus.Topic.csproj, src/Arcus.Messaging.Tests.Workers/Arcus.Messaging.Tests.Workers.csproj
Update Newtonsoft.Json package reference to use 12.0.1 since 12.0.0 does not exist
This is causing build warning:
> [...] Warning NU1603: Arcus.Messaging.Abstractions 1.0.1 depends on Newtonsoft.Json (>= 12.0.0) but Newtonsoft.Json 12.0.0 was not found. An approximate best match of Newtonsoft.Json 12.0.1 was resolved.
=> fix: Update Newtonsoft.Json package reference to use 12.0.1

docs/README.md
=> docs: typo in 'syntax highlighting'

docs/preview/02-Features/message-pumps/service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus.KeyRotation/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus.KeyRotation/ReAuthenticateOnRotatedCredentialsMessageHandler.cs
Mark the current key rotation functionality as obsolete as this is moved to Arcus BackgroundJobs.
Relates to #229
=> chore: mark keyrotation as obsolete

build/ci-build.yml, build/nuget-release.yml, build/templates/run-docker-integration-tests.yml
The release Docker integration tests weren't including the Azure Functions Docker test project which made the tests fail.
This fixes that and makes sure that future changes to these tests are by-default ported to the release build.
=> test: add az func tests to release build

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.AzureFunctions.ServiceBus/Arcus.Messaging.AzureFunctions.ServiceBus.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.Pumps.ServiceBus/KeyRotation/AzureServiceBusKeyRotation.cs, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj
Treat warnings as erors in messaging.
Relates to https://github.com/arcus-azure/arcus/issues/196
=> chore: treat warnings as errors

docs/preview/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.4.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.5.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.6.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v1.0.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v1.1.0/02-Features/message-pumps/service-bus.md
Fixes Markdown bold syntax in features docs for Azure Service Bus functions.
=> docs: fix wrong bold syntax for in az service bus functions

docs/preview/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.1.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.2.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.3.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.4.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.5.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v0.6.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v1.0.0/02-Features/message-pumps/service-bus.md, docs/versioned_docs/version-v1.1.0/02-Features/message-pumps/service-bus.md
Mention the Arcus secret store when explaining how Azure Service Bus message pumps should be registered.
=> docs: mention arcus secret store in az servicebus message pump

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Abstractions/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Abstractions/Telemetry/MessageCorrelationInfoEnricher.cs, src/Arcus.Messaging.Abstractions/Telemetry/ObsoleteMessageCorrelationInfoEnricher.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthService.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrderBatchMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusCompleteMessageHandler.cs, src/Arcus.Messaging.Tests.Workers/MessageHandlers/OrdersAzureServiceBusMessageHandler.cs
Since we need scoped correlation registration outside the message pump (see Azure Functions, where there is no message pump), we need to move to scoped correlation registration to the message router.
Closes #265
=> fix: add correlation registration in message router

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.AzureFunctions.ServiceBus/Arcus.Messaging.AzureFunctions.ServiceBus.csproj, src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj
Adds the GitHub README file to the NuGet package generation of the projects.
Adds feature docs project URL instead of GitHub URL to NuGet package.
Relates to arcus-azure/arcus#209
Relates to arcus-azure/arcus#208
=> chore: add readme and proj url to nuget pkg

src/Arcus.Messaging.ServiceBus.Core/ServiceBusMessageBuilder.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusMessageBuilderTests.cs
Adds method overload in Azure Service Bus message builder to include the operation ID as a custom application property.
Closes #279
=> feat: add operation id overload w custom prop name

src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpSettings.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
Informs the consumer about the Arcus secret store dependency when registering the Azure Service Bus message pump.
Follow-up of https://github.com/arcus-azure/arcus.backgroundjobs/issues/140
=> chore: inform consumer about secret store dependency

src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthListenerTests.cs
Remove the exception details from the health report from the exposed TCP health probe.
Closes #287
=> fix: rm exn details from tcp health probe

src/Arcus.Messaging.ServiceBus.Core/Extensions/ObjectExtensions.cs
Deprecated the extensions on the `object` type because we can now use the `ServiceBusMessageBuidler` to create `ServiceBusMessage` instance from an instance.
Closes #292
=> chore: deprecated object extensions

src/Arcus.Messaging.ServiceBus.Core/ServiceBusMessageBuilder.cs, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/Fixture/Order.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusMessageBuilderTests.cs
Relaxes the guards for correlation properties in the Azure Service Bus message builder.
Closes #293
=> fix: relax correlation properties guards in message builder

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Abstractions/Telemetry/MessageCorrelationInfoEnricher.cs
Use the message correlation model directly instead of doing a detour via the message correlation accessor.
This will make sure that we have the correct message correlation is used and will be more efficient and stable instead of going through the service provider.
Closes #301
=> feat: use message correlation model directly

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageCorrelationEnricherOptions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouterOptions.cs, src/Arcus.Messaging.Abstractions/Telemetry/MessageCorrelationInfoEnricher.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusQueueMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs
Make the Serilog log event properties that are being enriched from the message correlation model configurable, as they were using these constants `ContextProperties.xxx` previously.
Closes #303
=> feat: make message correlation enrichment properties configurable

docs/preview/02-Features/04-service-bus-extensions.md, src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj, src/Arcus.Messaging.ServiceBus.Core/Extensions/ServiceBusSenderExtensions.cs, src/Arcus.Messaging.ServiceBus.Core/ServiceBusSenderMessageCorrelationOptions.cs, src/Arcus.Messaging.Tests.Integration/ServiceBus/ServiceBusSenderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/ServiceBus/Fixture/InMemoryServiceBusSender.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusSenderExtensionsTests.cs
Add extensions on the Azure Service Bus `ServiceBusSender` model to more easily send and track correlated messages that support service-to-service correlation.
Closes #309
=> feat: add servicebus sender correlation extensions

src/Arcus.Messaging.Health/Tcp/TcpHealthListener.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
Improve the exception handling upon cancellation of the TCP health probe and Azure Service Bus message pump so that logging upon cancellation is not a mess.
Closes #311
=> chore: improve cancellation handling

src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
Fix typo in the XML code docs that reference the Arcus secret store when registering the Azure Service Bus message pump.
=> chore: fix typo in xml code docs on secret store ref

docs/preview/02-Features/04-service-bus-extensions.md, src/Arcus.Messaging.ServiceBus.Core/Extensions/ServiceBusSenderExtensions.cs, src/Arcus.Messaging.ServiceBus.Core/ServiceBusSenderMessageCorrelationOptions.cs, src/Arcus.Messaging.Tests.Integration/ServiceBus/ServiceBusSenderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusSenderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusSenderMessageCorrelationOptionsTests.cs
Adds contextual information in the form of a telemetry context to the Azure Service Bus sender correlation options so that the tracked Azure Service Bus dependency can be further configured.
Closes #327
=> feat: add telemetrycontext in sender correlation options

src/Arcus.Messaging.EventHubs.Core/EventHubProducerClientMessageCorrelationOptions.cs, src/Arcus.Messaging.EventHubs.Core/Extensions/EventHubProducerClientExtensions.cs, src/Arcus.Messaging.ServiceBus.Core/Extensions/ServiceBusSenderExtensions.cs, src/Arcus.Messaging.ServiceBus.Core/ServiceBusSenderMessageCorrelationOptions.cs
Changes the messaging-specific correlation model `MessageCorrelationInfo` with the general `CorrelationInfo` so that application from other environments (ex. HTTP) can also benefit from these extensions without having to convert to the messaging-specific model.
=> fix: use general correlation model in sender extensions

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.ServiceBus.Core/Extensions/ServiceBusReceivedMessageExtensions.cs, src/Arcus.Messaging.Tests.Runtimes.AzureFunction.ServiceBus.Queue/Functions/OrderProcessingFunction.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/MessageExtensionsTests.cs
Adds the `ServiceBusReceivedMessage` extensions to the same namespace as the message and deprecate the extensions in the old namespace.
Closes #339
=> chore: move servicebus message extensions to correct namespace

src/Arcus.Messaging.Abstractions/MessageHandling/MessageHandlerCollection.cs, src/Arcus.Messaging.Pumps.Abstractions/IRestartableMessagePump.cs, src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Pumps.EventHubs/Configuration/AzureEventHubsMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.EventHubs/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/EventHubsMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/EventHubs/IServiceCollectionExtensionTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs
Generalize restart functionality so that background jobs listening on events can more easily restart message pumps.
Closes #333
=> feat: generalize restartable message pumps

src/Arcus.Messaging.Abstractions.EventHubs/Extensions/EventDataExtensions.cs, src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Tests.Runtimes.AzureFunction.EventHubs/local.settings.json, src/Arcus.Messaging.Tests.Unit/EventHubs/EventDataBuilderTests.cs, src/Arcus.Messaging.Tests.Unit/EventHubs/EventDataExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/AzureEventHubsMessageRouterTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/Extensions/MessageContext.EventHubsMessageHandlerCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/Extensions/MessageContext.Message.EventHubsMessageHandlerCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/Extensions/MessageContext.MessageSerializer.EventHubsMessageHandlerCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/Extensions/MessageContext.MessageSerializer.Message.EventHubsMessageHandlerCollectionExtensionsTests.cs
Add extension on the `EventData` type to more easily retrieve the message context in EventHubs message handling scenarios.
Closes #345
=> feat: add eventhubs message context extension

.github/semantic.yml
We use a different way of PR validation. This file is still for the old deprecated GitHub action.
=> chore: remove deprecated pr config

docs/preview/02-Features/04-service-bus-extensions.md, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj, src/Arcus.Messaging.ServiceBus.Core/Extensions/AzureClientFactoryBuilderExtensions.cs, src/Arcus.Messaging.Tests.Integration/ServiceBus/AzureClientFactoryBuilderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/AzureClientFactoryBuilderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusSenderExtensionsTests.cs
Add extension overload to register a `ServiceBusClient` via a secret name corresponding with the Azure Service Bus connection string that is registered in the Arcus secret store.
Closes #358
=> feat: add servicebus client secretstore extension overload

docs/preview/02-Features/05-event-hubs-extensions.md, src/Arcus.Messaging.EventHubs.Core/Arcus.Messaging.EventHubs.Core.csproj, src/Arcus.Messaging.EventHubs.Core/Extensions/AzureClientFactoryBuilderExtensions.cs, src/Arcus.Messaging.Tests.Core/Generators/SensorReadingGenerator.cs, src/Arcus.Messaging.Tests.Core/Messages/v1/SensorReading.cs, src/Arcus.Messaging.Tests.Core/Messages/v1/SensorStatus.cs, src/Arcus.Messaging.Tests.Integration/EventHubs/AzureClientFactoryBuilderExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/EventHubs/AzureClientFactoryBuilderExtensionsTests.cs
Add extension overload to register a `EventHubsProducerClient` via a secret name corresponding with the Azure EventHubs connection string that is registered in the Arcus secret store.
#359
=> feat: add eventhubs producer client secretstore extension overload

build/ci-build.yml
Use the updated `main` in the CI build trigger.
Relates to https://github.com/arcus-azure/arcus/issues/169
=> chore: use `main` in CI build trigger

docs/preview/02-Features/06-general-messaging.md, src/Arcus.Messaging.Pumps.Abstractions/DefaultMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/IMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Pumps.EventHubs/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/EventHubsMessagePumpTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/MessagePump/DefaultMessagePumpLifetimeTests.cs, src/Arcus.Messaging.Tests.Unit/MessagePump/Fixture/TestMessagePump.cs
Add an `IMessagePumpLifetime` component that controls the message processing of registered message pumps so that the consumer can pause the message processing when the dependent downstream component can't keep up.
Closes #54
=> feat: add message pump lifetime

docs/preview/01-index.md, docs/versioned_docs/version-v1.3.0/01-index.md
Correct the introduction section in both the preview and published docs so it is in line with the component descriptions on the general site.
Relates to https://github.com/arcus-azure/arcus/pull/278
=> docs: correct introduction

.github/workflows/codeql-analysis.yml
Use default `main` branch in CodeQL workflow.
Relates to https://github.com/arcus-azure/arcus/issues/169
=> chore: use main branch in codeql

src/Arcus.Messaging.Pumps.Abstractions/DefaultMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/IMessagePumpLifetime.cs
Deprecate the faulted named `PauseMessagePumpAsync` in favor of `StartMessagePumpAsync`.
Relates to #387
=> fix: deprecate pause message pump lifetime

docs/preview/02-Features/04-service-bus-extensions.md, src/Arcus.Messaging.Abstractions.ServiceBus/AzureServiceBusMessageContext.cs, src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/ServiceBusReceivedMessageExtensions.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageContextTests.cs
Add the Azure Service Bus entity type to the request tracking within the Azure Service Bus message pump.
Closes #413
=> feat: add servicebus entitytype to req tracking

src/Arcus.Messaging.Pumps.Abstractions/DefaultMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/IMessagePumpLifetime.cs, src/Arcus.Messaging.Tests.Unit/MessagePump/DefaultMessagePumpLifetimeTests.cs
Rename the incorrect `IMessagePumpLifetime` method `Pause...` to `Start...`.
Closes #387
=> chore: rename incorrect 'pause' > 'start' in pump lifetime

docs/preview/02-Features/02-message-handling/01-service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/TopicSubscription.cs, src/Arcus.Messaging.Tests.Integration/Extensions/WorkerOptionsExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpDockerTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus.Topic/Program.cs
Change the default behaviour of the `AzureServiceBusMessagePump`.
Instead of automatically creating a subscription on startup by default, and removing the subscription again on shut-down, we no longer do that.
Closes #432
=> feat: do not automatically try to create and delete topic subscriptions

src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusQueueMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/AzureServiceBusMessagePumpOptionsTest.cs
Introduce the `Routing` member to the Azure Service Bus queue/topic message pump options interfaces, so that all the routing-related options are grouped together (and the `Telemetry` is available for configuratio).
Closes #431
=> chore: introduce routing options to service bus pump options interfaces

src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/EventHubs/AzureEventHubsMessageRouterTests.cs
Log the failure of not having the right message handler for the message, instead of throwing an `InvalidOperationException`. This is due to the fact that a throwal in a custom message handler still corresponds as a 'handled' message. The responsibility of the message router stops there.
This is different from having no matching message handlers registered, in that case, we can still throw such an exception.
Closes #424
=> chore: log io throw unhandled messages

build/nuget-release.yml
Forgot to add this to the Release pipeline, so that we still support .NET 6, while compiling.
=> chore: add prev dotnet sdk to release pipeline

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.Abstractions/Resiliency/DefaultMessagePumpCircuitBreaker.cs, src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs, src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs, src/Arcus.Messaging.Tests.Workers.EventHubs.Core/Arcus.Messaging.Tests.Workers.EventHubs.Core.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/Arcus.Messaging.Tests.Workers.ServiceBus.csproj, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/CircuitBreakerAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/OrdersSabotageAzureServiceBusMessageHandler.cs
Only when an incoming Azure Service bus message hasn't gone trhough a matching but failing message handler, should we throw if there were no fallback message handlers registered.
Closes #424
=> fix: only fail on fallback when az servicebus message wasn't tried

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs
The change in this PR reduces the 'noise' of logs that can be produced when a message-handler is unable to process a certain message.
When the message is abandoned due to an error, we assume that the developer already logs the necessary information and we don't want Arcus to always log an additional message.  Therefore, the loglevel of this specific trace has been changed to 'Debug'.
#457
=> fix: Reduce loglevel of certain traces

src/Arcus.Messaging.Abstractions.EventHubs/AzureEventHubsMessageContext.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/EventDataExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/EventHubsMessageHandlerExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/Message.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageContext.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageContext.Message.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageContext.MessageSerializer.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageContext.MessageSerializer.Message.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageSerializer.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/Extensions/MessageSerializer.Message.EventHubsMessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.AzureFunctions.EventHubs/AzureFunctionsInProcessMessageCorrelation.cs, src/Arcus.Messaging.AzureFunctions.EventHubs/Extensions/FunctionContextExtensions.cs, src/Arcus.Messaging.AzureFunctions.EventHubs/Extensions/IFunctionsHostBuilderExtensions.cs, src/Arcus.Messaging.EventHubs.Core/EventDataBuilder.cs, src/Arcus.Messaging.EventHubs.Core/EventHubProducerClientMessageCorrelationOptions.cs, src/Arcus.Messaging.EventHubs.Core/Extensions/AzureClientFactoryBuilderExtensions.cs, src/Arcus.Messaging.EventHubs.Core/Extensions/EventDataExtensions.cs, src/Arcus.Messaging.EventHubs.Core/Extensions/EventHubProducerClientExtensions.cs, src/Arcus.Messaging.Pumps.EventHubs/AzureEventHubsMessagePump.cs, src/Arcus.Messaging.Pumps.EventHubs/Configuration/AzureEventHubsMessagePumpConfig.cs, src/Arcus.Messaging.Pumps.EventHubs/Extensions/IServiceCollectionExtensions.cs
Remove all calls that use the Guard.NET library in the EventHubs-related projects.
Relates to #449
=> chore: remove guard.net references from eventhubs

docs/preview/02-Features/06-general-messaging.md, src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.Abstractions/Resiliency/IMessagePumpCircuitBreaker.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/Fixture/MockCircuitBreakerEventHandler.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePump.ResiliencyTests.cs
Because the `ICircuitBreakerEventHandler` implementations only took `MessagePumpCircuitState` during the transition of circuit breaker states, there was no easy way to know 1) for which message pump the state was changed and 2) what the original state was.
This PR wraps this information in an additional type.
=> feat(circuit-breaker): add job ID + old/new state change to circuit-breaker transition

src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/EventHubs/EventHubProducerClientExtensionsTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/MessageHandlerTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs, src/Arcus.Messaging.Tests.Unit/MessagePump/DefaultMessagePumpCircuitBreakerTests.cs, src/Arcus.Messaging.Tests.Unit/MessagePump/DefaultMessagePumpLifetimeTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/ServiceBusSenderExtensionsTests.cs
The unit test project was still using the older `Arcus.Testing` library to tracking logs in the test output.
This PR upgrades the unit test project to the new xUnit-specific logging package: `Arcus.Testing.Logging.Xunit`.
=> chore(deps): upgrade arcus.testing to v1.2 in unit tests

src/Arcus.Messaging.Tests.Unit/Arcus.Messaging.Tests.Unit.csproj, src/Arcus.Messaging.Tests.Unit/ServiceBus/ProcessMessageEventArgsExtensionsTests.cs
The unit test project had some compilation warnings related to the use of deprecated functionality and package range conflicts.
This PR resolves these warnings.
=> fix(warnings): in unit test project

src/Arcus.Messaging.Pumps.ServiceBus/TopicSubscription.cs
The `TopicSubscription` invalidly had the `[Flags]` attribute, which would indicate that the enumeration members could be used in combination with one another - which is not correct.
This PR removes the `[Flags]` attribute, making the intend of the enumeration more clear.
=> fix(service-bus): remove invalid flags attribute on topic subscription

src/Arcus.Messaging.Health/Arcus.Messaging.Health.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Tests.Integration/Arcus.Messaging.Tests.Integration.csproj
The Messaging abstractions projects were using older v6.x.x Microsoft packages, pinned to a specific version.
This PR uses version ranges to have a more clear intend on when users upgrade to a package higher than the upperbound (will result in restore failure insead of runtime `MethodNotFound` exception).
This PR also takes the opportiunity to use a the `x.Abstractions.Hosting` package instead, and to start using the v8.0.x range, as lowerbound in the package ranges.
Relates to #468
=> chore(deps): use version ranges for messaging abstractions

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.ServiceBus.Core/Extensions/MessageContextExtensions.cs
The `Arcus.Messaging.ServiceBus.Core` project will eventually be removed completely, as it only contains deprecated/old functionality. One of the extensions that is still used, is retrieving the encoding from the message context.
This PR inlines this functionality into the Azure Service bus message router so that we don't need the extension anymore, and deprecates the extension in the `.Core` library, so that anyone using this directly is aware of this.
=> chore(service-bus): deprecate service-bus encoding message-context extension

src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusClient.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusNamespace.cs, src/Arcus.Messaging.Pumps.ServiceBus/DefaultAzureServiceBusManagementAuthentication.cs, src/Arcus.Messaging.Pumps.ServiceBus/IAzureServiceBusManagementAuthentication.cs
Deprecates the functionality in the Service bus pump project that allows for rotation of conection strings. This used an older version of authentication, and is somewhat conflicting with the 'pump' project as it has little to do with message routing.
This PR deprecates all rotation-related functionality.
=> chore(sb): deprecate older rotate connection strings functionality

src/Arcus.Messaging.ServiceBus.Core/Extensions/ServiceBusReceivedMessageExtensions.cs
The entire `.ServiceBus.Core` project will be deprecated/removed, later. This PR deprecates the application property extension, as this is could be implicitly (pump project references the core project) be used by custom message handlers and deprecating it now will show that it will be removed later.
=> chore(sb): deprecate received message application property extension

src/Arcus.Messaging.Abstractions/Extensions/MessageBody.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageSerializer.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageSerializer.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageSerializer.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageSerializer.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/IMessageHandler.cs
Only concrete implementations of the message pump and message router will be available in the v3.0 space. This PR deprecates the message handler interface and registration with the general `MessageContext` so that it can be removed later on.
General message routing includes routing messages based on string instead of concrete types like ServiceBusReceivedMessage. The general message routing was required before when using it directly in Azure Functions, but since we removed the specific Azure Funcions support, we should remove this general message routing as well.
Relates to lightweight exercise described in https://github.com/arcus-azure/arcus.messaging/discussions/470
=> chore(general): deprecate general message context message handler

src/Arcus.Messaging.Abstractions.EventHubs/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.EventHubs/MessageHandling/AzureEventHubsMessageRouter.cs, src/Arcus.Messaging.Abstractions.EventHubs/MessageHandling/IAzureEventHubsMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/IAzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/IMessageRouter.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs
Only concrete implementations of the message pump and message router will be available in the v3.0 space. This PR deprecates the general message routing implementation and registration so that it can be removed later on.
General message routing includes routing messages based on `string` instead of concrete types like `ServiceBusReceivedMessage`. The general message routing was required before when using it directly in Azure Functions, but since we removed the specific Azure Funcions support, we should remove this general message routing as well.
Relates to lightweight exercise described in #470
=> chore(general): deprecate general message routing

src/Arcus.Messaging.Abstractions/Extensions/MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/IFallbackMessageHandler.cs
Only concrete implementations of the message pump and message router will be available in the v3.0 space. This PR deprecates the general fallback message handler interface and registration so that it can be removed later on.
General message routing includes routing messages based on string instead of concrete types like ServiceBusReceivedMessage. The general message routing was required before when using it directly in Azure Functions, but since we removed the specific Azure Funcions support, we should remove this general message routing as well.
Relates to lightweight exercise described in https://github.com/arcus-azure/arcus.messaging/discussions/470
=> chore(general): deprecate general fallback message handler

src/Arcus.Messaging.Pumps.Abstractions/Extensions/IMessagePumpCircuitBreakerExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.Abstractions/Resiliency/DefaultMessagePumpCircuitBreaker.cs
The pumps abstractions still had some references to the Guard.NET library. This PR removes those references in favor of built-in functionlity - not using the .NET 8 functionlity just yet as this is not availble in .NET Standard 2.1.
=> chore(deps): remove guard.net references from the pumps abstractions project

src/Arcus.Messaging.Abstractions/MessageContext.cs
As described in #470 , we are focusing solely on Service bus message routing, now. The concept of general message routing will be minimized. In the past, we had no need for a `JobId` during message routing, but with the arrival of specific Service bus operations, we did require it. It started with a new constructor on the `MessageContext` so that this job ID could be passed along. Only now, when we focus solely on Service bus, this older constructor is not needed anymore. This PR deprecates that older constructor.
=> chore(general): deprecate old general message context constructor

build/deploy-test-resources.yml, build/templates/test-resources.bicep
During the lightweight exercise described in #470 , the EventHubs-related projects are becoming deprecated, which means that we do not need to include them anymore in our continuous delivery pipeline (`deploy-test-resources.yml`).
This PR removes both the EventHubs-related references in the Bicep files, as well as the parameters passed along with it via the pipeline.
=> chore(cd): remove eventhubs-related resources from `deploy-test-resources.yml`

docs/preview/02-Features/02-message-handling/01-service-bus.md, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/TopicSubscription.cs
> 👉 This is a follow-up PR for #471.
It came to our attention that we only require a `ServiceBusAdministrationClient` in case of automatic Azure Service bus topic subscriptions. Because this functionality is not used very often in production, and should be in a 'Infrastructure-as-Code' deployment anyway to follow best practices, it is better to deprecate this functionality.
This PR deprecates the option and removes it from the feature documentation.
=> chore(service-bus): deprecate automatic az service-bus topic subscriptions

src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusQueueMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/IAzureServiceBusTopicMessagePumpOptions.cs
During the slimed-down exercise described in #470 , the focus will be on pure message routing/handling. Key rotation functionality will not be part of this core functionality.
The other key rotation functionality is already being made deprecated in another PR: #495, this PR deprecates the now unused option.
=> chore(service-bus): deprecate key rotation timeout option

src/Arcus.Messaging.Tests.Integration/Fixture/IntegrationTestHostingType.cs, src/Arcus.Messaging.Tests.Integration/Fixture/IntegrationTestType.cs
In a previous PR #446 the Docker integration tests were removed as to both simplify and centralize the responsibility of the Arcus.Messaging library. During that exercise, there were some leftover enumerations that are now being unused throughout the integration test project.
This PR removes those enumerations.
=> chore(docker): remove (now) unused/leftover test hosting types enums

src/Arcus.Messaging.Tests.Core/Arcus.Messaging.Tests.Core.csproj, src/Arcus.Messaging.Tests.Integration/MessagePump/Fixture/AssertX.cs
In previous versions, the integration tests used a custom way of polling for results in Application Insights during the test assertion of telemetry. These test polling operations are now being handled by Arcus.Testing, which means that we can remove any direct Polly reference.
This PR removes the Polly dependency and any remaining functionality that was using this in the integration test infrastructure.
=> chore(testing): remove unused polly dependency in tests

src/Arcus.Messaging.Abstractions/MessageHandling/MessageHandler.cs, src/Arcus.Messaging.Abstractions/MessageHandling/TypeNotFoundException.cs
A long time ago, code reflection was the only way to do message routing. The custom `TypeNotFoundException` exception class was introduced for a more user-friendly way of reporting not-found members.
Since we have stepped away from code reflection a long time ago, we can deprecate this exception and eventually remove it in v3.0.
=> chore(message-routing): deprecate custom type-not-found exception

src/Arcus.Messaging.Abstractions/MessageCorrelationResult.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
As described in the #470 discussion, the telemetry-specific concrete implementations will be removed from the core message routing functionality, making it possible to 'inject' certain telmetry solutions. As preperation of that exercise, all telemetry-specific functionality should be made deprecated.
This PR deprecates the specific constructor with the Application Insights `TelemetryClient` for the message correlation result.
=> chore(telemetry): deprecate telemetry-specific correlation result constructor

src/Arcus.Messaging.Abstractions/Extensions/MessageBody.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageSerializer.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageContext.MessageSerializer.MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageHandlerCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageSerializer.MessageBody.IServiceCollectionExtensions.cs, src/Arcus.Messaging.Abstractions/Extensions/MessageSerializer.MessageHandlerCollectionExtensions.cs
As described in the #470 discussion, the 'general messaging' will be deprecated in favor of concrete implementations. A previous PR #516 made sure that the references made to these general message handler registrations are minimized, which makes deprecating them in this PR more easy.
This PR deprecates all remaining 'general message handler' registrations in the solution, so they can be deleted in v3.0.
=> chore(general): deprecate remaining message handler registrations

src/Arcus.Messaging.Abstractions/PropertyNames.cs
As described in the #470 discussion, the 'Hierarchical' correlation format is being made deprecated in v2.2 and removed in v3. This was already partly done in previous PR's, like #485.
This PR deprecates the content-type property name that was solely used in the `ServiceBusMessageBuilder` - which in turn is also made deprecated as it was only used within 'Hierarcical' contexts.
=> chore(observability): deprecate hierarchical content-type property name

src/Arcus.Messaging.Pumps.Abstractions/MessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
As described in the #470 discussion, the core messaging functionality is being reviewed. A part of that exercise is to review the 'general' messaging. Previous PR's already deprecated sevaral parts of this, like #498.
This PR deprecates additional, old, message pump information that was added in one of the first versions of the message pump, that still leaked concrete information to the general abstraction, like an `EntityPath` property.
=> chore(general): deprecate unnecessary general message pump information

src/Arcus.Messaging.Abstractions/Extensions/IDictionaryExtensions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/FallbackMessageHandler.cs, src/Arcus.Messaging.Tests.Integration/Extensions/WorkerOptionsExtensions.cs, src/Arcus.Messaging.Tests.Integration/Fixture/TemporaryManagedIdentityConnection.cs, src/Arcus.Messaging.Tests.Integration/Fixture/Worker.cs, src/Arcus.Messaging.Tests.Integration/Fixture/WorkerOptions.cs, src/Arcus.Messaging.Tests.Integration/Health/TcpHealthService.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBus/TestServiceBusMessageProducer.cs, src/Arcus.Messaging.Tests.Unit/Extensions/ObjectExtensions.cs, src/Arcus.Messaging.Tests.Unit/Fixture/TestMessageBodySerializer.cs
As described in #449 , the Guard.NET will no longer be something that is baked into the Messaging library. Since this dependency is also transient via the Arcus.Observability package, some `using`s and test infrastructure code still had references to Guard.NET. This PR removes those.
=> chore(deps): remove leftover & unused guard.net references

src/Arcus.Messaging.Abstractions/MessageCorrelationResult.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs
As partly described in #470, the Hierarchical format will be made deprecated in v2.2 and removed in v3.0. Previous PR's already made parts of it usage obsolete, like #485.
This PR deprecates the constructor for the `MessageCorrelationResult` that's only used for hierarhical purposes.
=> chore(observability): deprecate hierarchical message correlation result constructor

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions/IMessageCorrelationInfoAccessor.cs, src/Arcus.Messaging.Abstractions/MessageCorrelationInfoAccessor.cs
As discussed in #470, the core messaging will solely focus on message handling/routing, which makes the hard-linked dependencies to Arcus.Security, Arcus.Observability, Serilog and Application Insights deprecated in the abstractions library. Previous PR's already deprecated Serilog and Arcus.Security functionality, like #491.
This PR deprecates the Arcus.Observability correlation accessor implementation, as this is a rather unnecessary implementation, since the correlation will already be provided via the message routing.
=> chore(observability): deprecate message correlation accessor

src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/IAzureServiceBusMessageRouter.cs
As described in the discussion #470, the message pump-free scenarios like Azure Functions will be removed from support in favor of using the message pump as the sole point of contact for message processing. There was a Azure Service bus overload that was only used in those scenarios. This PR deprecates that overloads, so it can be removed in v3.0.
=> chore(message-router): deprecate az func-only az service-bus message-router overloads

src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/IServiceCollectionExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
As described in the discussion #470, the Azure Functions-support will be removed in v3.0. This means that message router-only functionality/regisrataions are now unnecessary.
This PR deprecates the registrations of the Azure Service bus message router, in favor of using the constructor, in v3.0.
=> chore(message-router): deprecate az func-only az service-bus message-router registrations

src/Arcus.Messaging.Abstractions/MessageHandling/MessageCorrelationEnricherOptions.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageCorrelationFormat.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageCorrelationOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
As described in the discussion #470 , the core messaging functionality will not hold specific correlation systems, which makes all correlation-specific options deprecated within the core messaging.
This PR deprecates the remaining message correlation properties that only make sense in a specific correlation system: W3C.
=> chore(correlation): deprecate general message correlation options

src/Arcus.Messaging.Abstractions.ServiceBus/AzureServiceBusMessageContext.cs, src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/ServiceBusReceivedMessageExtensions.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
As described in the #470 discussion, we will need to have enrich the Azure Service bus context if we want to let custom correlation systems track the request.
This PR adds a new factory method to the message context, making it the single point of contact for creating contexts.
=> feat(az.sb.ctx): add fqn & entity type to az service-bus context

docs/docusaurus.config.js, docs/preview/03-Guides/migration-guide-v3.0.md
In a previous phase, the Azure Service bus message pump registration was reviewed and simplified to handle a dependency-less approach without overload the user with overloads.
This PR adds this new way of registering the message pump to the v3.0 migration guide.
Relates to #506
=> docs(migration.v3.0): add new service-bus message pump registration to v3.0 migration guide

build/ci-build.yml
Since we use the `ubuntu-latest` in our CI pipelines, it notified us that the current approach on pushing NuGet packages to our MyGet feed (which gets pushed on every open PR), is now not working anymore with the newest Ubuntu release (v24.04).
Because of this, and the fact that we use YAML templates to streamline throughout Arcus repo's, we are left with a broken CI build.
This PR removes the YAML template in favor of a custom `dotnet nuget` command, as this will both fix the CI build, as well as removing a bit of unnecessary relationship with other Arcus repo's. It allows for Arcus repositories to grow more on their own, and to fix issues (like these) more quicker, without the overhead of other repo's. The downside, is that there might be some duplicated code, but since the amount of …
=> fix(ci): use custom dotnet command for myget preview release

src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs, src/Arcus.Messaging.Pumps.ServiceBus/Extensions/IServiceCollectionExtensions.cs
As described in discussion #470, the message correlation system choice should be extracted from the core messaging functionality. The plan is to expose an interface that can be implemented by specific message correlation systems. Interacting with this interface will be done in the message pump, therefore, the telemetry options to manipulate the message correlation should also be in the message pump options.
This PR creates a new `.Telemetry` options property in the Azure Service bus message options, which should be used instead of the (now) deprecated `.Routing.Telemetry` options. Making it more clear, correct and maintainable.
=> feat(az.sb.telemetry): add telemetry options alternative in message pump options

src/Arcus.Messaging.Abstractions.ServiceBus/AzureServiceBusMessageContext.cs, src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/ServiceBusMessageHandlerExtensions.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageHandlerTemplate.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/AzureServiceBusMessageRouter.cs, src/Arcus.Messaging.Abstractions.ServiceBus/MessageHandling/IAzureServiceBusFallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions/MessageHandling/FallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions/MessageHandling/IFallbackMessageHandler.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageHandlerCollection.cs, src/Arcus.Messaging.Abstractions/MessageHandling/MessageRouter.cs, src/Arcus.Messaging.Pumps.ServiceBus/Resiliency/CircuitBreakerServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/AbandonAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/CompleteAzureServiceBusMessageHandler.cs, src/Arcus.Messaging.Tests.Workers.ServiceBus/MessageHandlers/DeadLetterAzureServiceMessageHandler.cs
Moves the Azure Service bus-specific operations (Complete, Abandon, Dead-Letter) to the message context, so that the following functionality can be made deprecated:
* Azure Service bus message template classes for regular/fallback message handlers, as these were solely used to trigger the Azure Service bus operations;
* General fallback functionality, as this is now also unnecessary for any of the 'messaging' implementations;
Relates to #547
=> feat(sb): move service-bus operations to message-context

src/Arcus.Messaging.Pumps.Abstractions/DefaultMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/IMessagePumpLifetime.cs, src/Arcus.Messaging.Pumps.Abstractions/IRestartableMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/AzureServiceBusMessagePump.cs, src/Arcus.Messaging.Pumps.ServiceBus/Configuration/AzureServiceBusMessagePumpOptions.cs
As first mentioned in the discussion #470 and re-confirmed in #546 , the `IMessagePumpLifetime`/`IRestarableMessagePump` are deprecated since their initial purpose was to be able to provide a system to 'pause' the message pump when the external dependency system can't keep up - which is exactly what the new circuit breaker functionality provides.
=> chore(general): deprecate message pump lifetime restartable functionality

build/nuget-release.yml
Since the new Ubuntu build image on DevOps does not have `mono` installed, it means that some tools like **NuGet** are not built-in installed anymore. As a migration, they recommend doing it yourself.
This PR uses the `dotnet nuget push` instead (like we did with the MyGet release), which fixes this problem.
=> fix(release): use custom `dotnet nuget push` for NuGet release

build/templates/integration-tests.yml
The CI pipeline still had references to EventHubs Key Vault secrets, this PR removes these.
=> chore(ci): remove event-hubs key-vault secrets from ci

docs/preview/02-getting-started.md, docs/preview/03-Features/01-Azure/01-service-bus.md
Use docusaurus admonitions to highlight certain paragraphs instead of less visible Markdown quotes.
=> docs(para.highlight): use docusaurus admonitions to highlight paragraphs

src/Arcus.Messaging.Abstractions.ServiceBus/Arcus.Messaging.Abstractions.ServiceBus.csproj, src/Arcus.Messaging.Abstractions/Arcus.Messaging.Abstractions.csproj, src/Arcus.Messaging.Pumps.Abstractions/Arcus.Messaging.Pumps.Abstractions.csproj, src/Arcus.Messaging.Pumps.ServiceBus/Arcus.Messaging.Pumps.ServiceBus.csproj, src/Arcus.Messaging.ServiceBus.Core/Arcus.Messaging.ServiceBus.Core.csproj, src/Arcus.Messaging.Tests.Core/Arcus.Messaging.Tests.Core.csproj
> 👉 Since we're working on v3.0, we can start removing stuff for real.
This PR removes all .NET 6 and .NET Standard 2.1 target frameworks from the message-processing projects (excluding Health).
Relates to #484
=> chore(.net): remove net6.0 & netstandard2.1 from message processing projects

src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/ServiceBusMessageHandlerExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePump.RouterTests.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePump.ServiceBusTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs, src/Arcus.Messaging.Tests.Unit/ServiceBus/IServiceCollectionExtensionsTests.cs
> 👉 Since we're working on the v3.0 release, we can start removing stuff for real.
This PR removes the Azure Service Bus fallback message handler registration from the codebase, which means that no fallback message handlers can be registered in the message routing. The fallback message handling functionality was an old idea of having a way to easily place Azure Service Bus operations in a dedicated message handler, but with the moving of those operations to the message context (#551), we allow for a more easy access to those operations and more flexibility to the developer, without implementating dedicated message handlers.
Relates to #484
=> chore(az.sb): remove deprecated az sb fallback message handler registrations

build/variables/build.yml
We should solely use .NET 8 now, so we don't have to use a previous version just yet.
This PR removes this from the pipelines by updating the variables.
=> chore(deps): solely use .NET 8 in pipelines

src/Arcus.Messaging.Abstractions/PropertyNames.cs
Remove `OperationParentId` from `PropertyNames`.
=> chore(messaging.abstractions): remove propertynames.operationparentid

docs/preview/03-Features/01-Azure/01-service-bus.md, docs/preview/03-Guides/migration-guide-v3.0.md, src/Arcus.Messaging.Abstractions.ServiceBus/Extensions/ServiceBusMessageHandlerOptions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/Fixture/ServiceBusMessageHandlerCollectionTestExtensions.cs, src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePump.RouterTests.cs, src/Arcus.Messaging.Tests.Unit/MessageHandling/ServiceBus/AzureServiceBusMessageRouterTests.cs
Corrects the behind-the-scenes functionality and naming of the Azure Service Bus message handler options to more reflect what is expected from an user-perspective:
* Multiple calls to `options.Add...Filter` should be aggregated into an AND expression;
* `options.UseMessageBodySerializer` more correctly shows that only a single instance is used, instead of `options.Add...` 
This PR also immediately provides the easy-access message body serializer overload, described in #622.
Closes #623 
Closes #622
=> chore(az.sb): correct az sb msg handler options naming+aggregation

docs/preview/03-Features/01-Azure/01-service-bus.md
Adds warning on `options.AutoComplete` to point to the fact that consumers are responsible for completing the message themselves, if not auto-completing it.
=> docs(az.sb): Update Autocomplete documentation on Service Bus Arcus.Messaging

src/Arcus.Messaging.Tests.Integration/MessagePump/ServiceBusMessagePumpTests.cs
The Azure Service Bus queue with session-support was not teared down in the integration tests, this PR fixes that.
=> fix(az.sb.test): add missing queue w/ session teardown

docs/preview/03-Features/01-Azure/01-service-bus.mdx, docs/preview/03-Guides/migration-guide-v3.0.md
In a previous PR #644 , the Serilog correlation was moved to a separate project, but some minor details were not being passed to the feature documentation. This PR fixes that.
=> docs(az.sb): update docs w/ recent serilog correlation scope changes
